# Site settings
title: Acusp's Blog
email: acusp.xu@gmail.com
description: acusp;blog# this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://acusp.info" # the base hostname & protocol for your site
twitter_username: acusp_xu
github_username:  acusp

# Build settings
markdown: kramdown
highlighter: pygments
