# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true
gems: 				 [jekyll-paginate]

# Setup
title:               Absorb
tagline:             acusp's blog
description:         ''
url:                 http://acusp.info
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Acusp Xu
  url:               https://twitter.com/acusp_xu
  email:             acusp.xu@gmail.com

# Build settings
markdown: redcarpet
highlighter: pygments
